export const title = '.step-title';
export const email = 'Email Address *';
export const cart_menu_icon = '#menu-cart-icon';
export const password = 'Password *';
export const firstname = 'First Name';
export const lastname = 'Last Name';
export const street_address = 'Street Address: Line 1';
export const city = 'City';
export const state = 'select[name="region_id"]';
export const postcode = 'Zip';
export const telephone = 'Phone Number';
